dect = None
i = None


def word_get(str:dect, int:i):
    Dictionary = {'Lexus': ['GX 470', 'ES 350', 'ES330', 'LS460', 'ES 330', 'Is 250', 'Is 350', 'Es 300', 'RX 350', 'RX 330', 'Rx 300', 'Rx 330', 'LX 570', 'Gx 460', 'Gx 470', 'GS 430', 'GS 350', 'Gs 330', 'Lx', 'Es', 'Lx 570', 'Es 350', 'Lx 470', 'Gx460', 'Rx 330', 'Rx 350', 'Es 330', 'IS 200T', 'CT 200h', 'Ls', 'Gx470', 'Gs 300', 'Gx', 'Rx', 'Gs', 'Is250', 'NX'],
                  'Mazda': ['323', 'Premacy', 'Tribute', 'Cx-9', 'Cx-7', 'PRIMACY', 'MX-5 Miata', '6', '5', '3', 'Mpv'],
                  'BMW': ['M6', '7 Series', '6 Series', '5 Series', '3 Series', '1 Series', '626', 'X1', 'X3', 'X5', 'X6', 'Z3', '325I', '320i', '330XI'],
                  'Nissan': ['Xterra', 'Sentra', 'Versa', 'X-Trail', 'Primera', 'Teana', 'Altima', 'Murano', 'Titan', 'Qashqai', 'Maxima', 'Frontier', 'Rogue', 'Pathfinder', 'Urvan', 'Almera', 'Vanette', 'INFINITY', 'Kicks', 'Cefiro', 'Civilian', 'Sunny', 'SENTRA', 'Quest', 'Patrol', 'Armada'],
                  'Mercedes-Benz': ['C 350', 'C200', 'A180', 'B180', 'E320', 'E240', 'GL 450', 'GLC 300', 'E550', 'E350', 'Vito', 'CLA250', 'C320', 'S500', 'S550', 'S350', 'GLE350', 'G500', 'E230', 'E280', 'E350', 'E500', 'E200', 'CLS 350', 'C180', 'C230', 'C 240', 'C280', 'GLE', 'C200 KOMPRESSOR', 'C250', 'C240', 'C350', 'R350', 'Gl550', 'E300', 'C 300', 'GLK 350', 'C 230', 'ML 350', 'GL450', 'R500', 'G550', 'Cl500', 'Gl420', 'Glk350', 'C220 Cdi', 'C-CLASS', 'M-CLASS', 'a170', 'Sprinter', 'Ml63 Amg', 'E43', 'Ml550', 'C 240', 'G Class', 'E 200', 'A140', 'Clk500', 'A160', 'Glk250', 'ML 350', 'Ml320', 'Gl350', 'Gl450', 'C63 Amg', 'Clk200', 'Gl500', 'Ml350', 'Slk350', 'E430', 'S600', 'C43', 'GL-CLASS'],
                  'Toyota': ['Sienna', 'Fortuner', 'Avanza', 'Prius', 'Land Cruiser', 'Auris', 'Matrix', 'Fj Cruiser', 'Hilux', 'Tundra', 'Avalon', 'Celica', '4Runner', 'Solara', 'Avensis', 'Sequoia', 'Yaris', 'HiAce', 'Landcruiser Prado', 'Prado', 'Corolla', 'Venza', 'Camry', 'CAMRY (HYBRID)', 'RAV4', 'Corolla verso', 'Corona', 'Highlander', 'Tacoma', 'Picnic', 'BUS', 'ipsum', 'HARRIER', 'VERSO', 'Echo', 'Land Cruiser Prado'],
                  'Toyota Lexus': ['RX 450h'],
                  'Ford': ['Mustang', 'E-Series', 'Freestyle', 'Taurus', 'Transit', 'E150', 'Expedition', 'Ranger', 'Ecosport', 'Focus', 'Explorer', 'Escape', 'Edge', 'X5', 'Windstar', 'F-150', 'Mondeo', 'Everest', 'Flex', 'SMAX', 'Fusion', 'Econoline', 'E-350'],
                  'Honda': ['Accord', 'CRV', 'Accord Crosstour', 'Fit', 'Jazz', 'Ridgeline', 'City', 'Odyssey', 'Pilot', 'Cr-V', 'Civic', 'XC60', 'XC90'],
                  'Kia': ['Forte', 'Amanti', 'Cerato', 'Cadenza', 'Sedona', 'Carens', 'Soul', 'Sorento', 'Mohave', 'Sportage', 'K', 'Quoris', 'JOICE', 'Rio', 'Optima', 'Carnival'],
                  'Acura': ['Tlx', 'Tl', 'Rl', 'Rdx', 'Zdx', 'Mdx', 'mdx'],
                  'Volvo': ['V40', 'Xc70', 'Xc90', 'S80', 'S60', 'S40', 'XC 60', 'V60', 'V70'],
                  'Volkswagen': ['Touareg', 'Beetle', 'Amarok', 'LT 35', 'CC', 'Jetta', 'Passat', 'Tiguan', 'Golf', 'TRANSP SHUTTLE', 'Touran', 'Sharan', 'Polo', 'Rabbit'],
                  'Chevrolet': ['Avalanche', 'Optra', 'Venture', 'Malibu', 'Camaro', 'Epica', 'Equinox', 'Trax', 'Cruze', 'Aveo', 'Express Cargo', 'REZZO', 'Tracker', 'Uplander', 'NUBIRA', 'Trailblazer', 'Traverse'],
                  'Dodge': ['Avenger', 'Caliber', 'Caravan', 'Challenger', 'Charger', 'Durango', 'Journey', 'Ram Promaster', 'Ram'],
                  'Mitsubishi': ['Outlander', 'Space Wagon', 'Montero', 'Pajero', 'L200', 'L300', 'L400', 'Attrage', 'Galant', 'Lancer', 'Space gear', 'SpaceStar', 'Endeavor'],
                  'Peugeot': ['807', '607', '508', '406', '407', '408', '307', '306', '304', '301', 'Expert', '207', 'BOXER'],
                  'Infiniti': ['Fx', 'Qx', 'FX35', 'Qx56', 'G35', 'G35X', 'QX4', 'M', 'G', 'G37'],
                  'Buick': ['Lacrosse', 'Enclave'],
                  'Renault': ['Duster', 'Scenic', 'Laguna', 'Megane', 'ESPACE', 'Escape'],
                  'Jeep': ['Compass', 'Grand Cherokee', 'Commander', 'Cherokee', 'Liberty', 'Wrangler'],
                  'Ssangyong': ['Rexton', 'actyon', 'Actyon'],
                  'Skoda': ['Octavia', 'Superb', 'Fabia'],
                  'Audi': ['A6', 'A5', 'A4', 'Q7', 'Q5', 'Tt'],
                  'BMW': ['3 Series'],
                  'Subaru': ['Outback', 'Impreza', 'Forester', 'Legacy'],
                  'Lincoln': ['Mkx', 'Navigator', 'Town Car', 'Mks', 'Mkv'],
                  'Saturn': ['VUE', 'AURA', 'Outlook'],
                  'Opel': ['Tigra', 'Zafira', 'Astra', 'FRONTERA', 'Signum'],
                  'Suzuki': ['Every Wagon', 'Sx4', 'Forenza', 'Swift', 'XL7', 'Kizashi', 'XL-7', 'Vitara', 'Grand Vitara'],
                  'GAC': ['GS4', 'GA3-S', 'GS5', 'GA 4'],
                  'Chrysler': ['Voyager', '200', 'Pacifica', 'Pt Cruiser', 'Town & Country', 'Sebring', '300'],
                  'Brilliance': ['Splendor'],
                  'GMC': ['Savana', 'Sierra', 'Acadia'],
                  'Innoson': ['IVM G80', 'IVMG5'],
                  'MG': ['350s'],
                  'Dacia': ['406'],
                  'Ashok': ['Leyland'],
                  'Jaguar': ['X-Type', 'XE', 'Xj', 'S-Type', 'Xk'],
                  'Cadillac': ['Srx', 'Escalade', 'Cts'],
                  'range rover': ['HSE'],
                  'RANGE ROVER': ['VELAR'],
                  'Renault': ['Escape'],
                  'JMC': ['NEW CARRYING LIGHT DUTY TRUCK'],
                  'Fiat': ['ducato', 'FULLBACK'],
                  'Seat': ['Cordoba'],
                  'Citroen': ['BERLINGO'],
                  'Landrover': ['HSE SPORTS'],
                  'Land Rover': ['Lr4', 'Lr3', 'Lr2', 'Range Rover Vogue', 'Freelander', 'Discovery'],
                  'Bentley': ['Continental'],
                  'Geely': ['CK'],
                  'Rover': ['600'],
                  'Daihatsu': ['MOVE'],
                  'Hummer': ['H3'],
                  'Stallion': ['Force'],
                  'Pontiac': ['SALOON', 'Montana', 'Vibe'],
                  'Tata': ['407'],
                  'Isuzu': ['Rodeo'],
                  'Foton': ['VIEW CS2'],
                  'Porsche': ['Boxster', 'Cayenne'],
                  'Hyundai': ['Trajet', 'Azera', 'Genesis', 'Veloster', 'Tiburon', 'Tucson', 'I10', 'H1', 'Ix35', 'Santamo', 'Accent', 'Creta', 'Elantra', 'Santa Fe', 'Veracruz', 'Sonata', 'Entourage'],
                  'Mercury': ['Villager'],
                  'Ashok': ['Leyland']
                  }
    
    word = Dictionary[dect][i]
    return word
